name: Sync Image to Aliyun  Example

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Git pull
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: crpi-b3hn9ts05cp0mm2k.cn-chengdu.personal.cr.aliyuncs.com
        username: ${{secrets.OPTIMIST_USERNAME}}
        password: ${{secrets.OPTIMIST_PASSWORD}}
        logout: false

    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
         skopeo copy docker://docker.io/library/tdengine/tdengine:3.3.2.0 docker://crpi-b3hn9ts05cp0mm2k.cn-chengdu.personal.cr.aliyuncs.com/base-common-image/tdengine/tdengine:3.3.2.0
         skopeo copy docker://docker.io/library/rabbitmq:management docker://crpi-b3hn9ts05cp0mm2k.cn-chengdu.personal.cr.aliyuncs.com/base-common-image/rabbitmq:management
         skopeo copy docker://docker.io/library/bitnami/kafka:3.3.2 docker://crpi-b3hn9ts05cp0mm2k.cn-chengdu.personal.cr.aliyuncs.com/base-common-image/bitnami/kafka:3.3.2
         
         
         
